### ISSUE TITLE
[BUG] Burp Suite Advanced Scope Contorl does not apply theme

### ISSUE THREAD

**Issue by Devi0usM0nk** [CoreyD97/BurpCustomizer#6] opened 2021-01-14 12:38 UTC
**Describe the bug**

**To Reproduce**
Do the following after applying theme
1. Go to 'Target tab'
2. Go to 'Scope tab'
3. Click on 'Use advanced Scope Contorl'

**Expected behavior**
Theme Should have been applied

**Screenshots**
![2021:01:14:18:00:48](https://user-images.githubusercontent.com/38492444/104591500-c6798a00-5692-11eb-8977-d2715e74a597.png)

**Versions (please complete the following information):**
 - OS: [e.g. iOS] Manjaro
 - Burp Suite Pro / Community
 - Burp Suite Version [e.g. 2020.11]
 - Theme One Dark

**Comment by CoreyD97** [comment] 2021-01-14 13:20
This issue is a duplicate of #4, but thanks for the additional information you've provided :+1:

**Closed by CoreyD97** 2021-01-14 13:20 UTC
Labels: bug
